name: flutter_fitness_app
description: A fitness App for Flutter.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  provider: ^4.3.2+3
  json_annotation: ^3.1.1
  http: ^0.12.2
  connectivity: ^2.0.2
  flutter_reorderable_list: ^1.0.0
  font_awesome_flutter: ^9.0.0
  flutter_hooks: ^0.16.0
  percent_indicator: ^3.0.1
  # audioplayers: ^0.17.4
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.11
  json_serializable: ^3.5.1
  flutter_launcher_icons: ^0.8.1
  flutter_native_splash: ^0.3.0

flutter:

  uses-material-design: true
  assets:
    - images/
    - assets/

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

flutter_native_splash:
  image: images/splash.png
  color: "000000"                           #
  android_disable_fullscreen: true
  
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/app_icon_square.png"
